# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9893b86fae54caa6884e37fe16a16cf131663ead24c08756c545e8ec1657d8edc45bbbea11c7c920906e0dd4608639cb1c7f04e865d45c2dec4683d4e53e0e9c

test:
  secret_key_base: a22849adbf40b1fbd79edbd7a6feaade96e89a012f254cc3f4f32729abefc1789634a010a2355eac948ae04ebb4ef84432ac2cf36ae179a2c4012390da22d9eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
